### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by maticstric** [weijia-cheng/leo-tolstoy_what-is-art_aylmer-maude#1]
typogrify:
- [x] Accept everything

modernize-spelling:
- [x] There’s one change in chapter 10 (a la -> à la) which should probably be accepted since that’s the French spelling
- [x] In chapter 17, “grownup” should be “grown-up” since it’s used as an adjective

clean:
- [x] After typogrifying the headers in chapter 10, clean makes changes which should be accepted

build-toc:
- [x] Makes changes which should be accepted

Italics
- [x] In chapter 11 crescendo and arpeggio are in `<em>` tags. Those were probably just italicized, not emphasized, since they come from Italian and the emphasis doesn’t really seem to fit. Remove italics here since these are both in MW
- [x] In chapter 13 you have an `<i>` tag around “à la Guillaume Tell”. Guillaume Tell is an opera (https://en.wikipedia.org/wiki/William_Tell_(opera)) so it should have opera semantics. The “à la” can lose italics since it’s in MW (https://www.merriam-webster.com/dictionary/%C3%A0%20la)
- [x] In chapter 5 the letters “a” and “b” are italicized 4 times. They shouldn’t be according to https://standardebooks.org/manual/1.6.2/single-page#8.2.8.2

Additional changes:
- [x] All chapter bodies should have their epub:type changed from “z3998:fiction” to “z3998:non-fiction” 
- [x] In chapter 10 those dots in the Verlaine poem represent the elided parts. They should be styled as specified here: https://standardebooks.org/manual/1.6.2/single-page#7.5.7. Same goes for the endnote with the translation where you just made it two separate verses. You can also remove the css you added for the endnotes to separate the two verses
- [x] In chapter 10 the paragraph starting with “Si un être…” the `<p>` tag should have the xml:lang instead of the `<i>` tag (https://standardebooks.org/manual/1.6.2/single-page#5.3.1.3)
- [x] In chapter 10 for the No. XXXVI Duellum poem it seems weird to have nested xml:langs, one French and one Latin? This might be correct I just don’t know, so unless you’re sure you should ask on the mailing list
- [x] In chapter 10 the Favart epigraph doesn’t need xml:lang since the parent blockquote has it. This will also restore the italics to that epigraph which aren’t there at the moment because of the css
- [x] In the appendix II, those “No.” arabic ordinals, as well as the arabic ordinals within the Blue Bird poem, might be better as `<h_>` tags with Roman numerals. Probably consult Alex on this one, but he usually prefers Roman numerals
- [x] In the appendix II you can add `<br/>` in the cite tag after “Verhaeren” and “Fezensac” to better match the scans
- [x] In the introduction, you semanticate the Sequel and Postscript to The Kreutzer Sonata as books. I can’t find any references to this Sequel and Postscript online, so I don't know what the semantics should be, but I doubt they should be semanticated as books. Did you try doing any research on this?
- [x] I would personally remove the links to chapters in the introduction (not the pages, those have to stay). I think they’re unnecessary. The table of contents is always close by and the blue text seems distracting. Same goes for the links to the Appendix that you have in a couple of places. But this might just be me

**Comment by weijia-cheng** [comment]
I've made most of these changes, but there are a few I don't think should be made:

> There’s one change in chapter 10 (a la -> à la) which should probably be accepted since that’s the French spelling

This is how it is spelled in the original French: https://fr.wikisource.org/wiki/Le_Galant_Tireur

>  In chapter 11 crescendo and arpeggio are in `<em>` tags. Those were probably just italicized, not emphasized, since they come from Italian and the emphasis doesn’t really seem to fit. Remove italics here since these are both in MW

I agree that crescendo is not emphasized and have removed it, although I think the emphasis on arpeggio needs to stay. I think the noun "arpeggio" is being used here in a very strange way, like as an adjective describing "sounds," and the emphasis helps to clarify that there is an unusual word order with emphasis on arpeggio here.

>  In chapter 13 you have an `<i>` tag around “à la Guillaume Tell”. Guillaume Tell is an opera (https://en.wikipedia.org/wiki/William_Tell_(opera)) so it should have opera semantics. The “à la” can lose italics since it’s in MW (https://www.merriam-webster.com/dictionary/%C3%A0%20la)

If you look at Chapter 11, "à la Guillaume Tell" is a quote taken from a book that Tolstoy reviewed, so I am a little hesitant to remove italics from this since it is a coherent French phrase that came from a French-language context. I don't know if I would draw the conclusion that this is referring to the opera, since this could be referring to Schiller's play or just the actual mythological figure. 

>  In chapter 5 the letters “a” and “b” are italicized 4 times. They shouldn’t be according to https://standardebooks.org/manual/1.6.2/single-page#8.2.8.2

I think that rule is saying if you are referring to the letters as letters, but this is an unsemantic usage of italics for bullets in an inline list, so I think the italics should stay.

>  In chapter 10 those dots in the Verlaine poem represent the elided parts. They should be styled as specified here: https://standardebooks.org/manual/1.6.2/single-page#7.5.7. Same goes for the endnote with the translation where you just made it two separate verses. You can also remove the css you added for the endnotes to separate the two verses

I see what you mean about the two verses in the endnote, and have made that change, though I don't think the ellipses in the Verlaine poem represent elision. The original text of ["Art poétique"](https://fr.wikipedia.org/wiki/Art_po%C3%A9tique_(Verlaine)) has an ellipse in the last stanza. (Unless you are referring to something else? The original text of the Ariette Oubliées also has an ellipse: https://www.poemes.co/ariettes-oubliees.html

For the rest, I have questions I'll pitch to Alex. :)

**Comment by maticstric** [comment]
> This is how it is spelled in the original French: https://fr.wikisource.org/wiki/Le_Galant_Tireur

Good.

> I agree that crescendo is not emphasized and have removed it, although I think the emphasis on arpeggio needs to stay. I think the noun "arpeggio" is being used here in a very strange way, like as an adjective describing "sounds," and the emphasis helps to clarify that there is an unusual word order with emphasis on arpeggio here.

I agree that it's being used in a strange way since arpeggio is usually a noun, but I think it can be used as an adverb (if that's what it is) as well. As in "to play a chord arpeggio".

I found a couple of examples with a quick google search:
1. https://www.google.com/books/edition/The_Musical_Herald_and_Tonic_Sol_fa_Repo/ld8qAAAAYAAJ?hl=en&gbpv=1&dq=%22play+the+chord+arpeggio%22&pg=PA90&printsec=frontcover
2. https://www.google.com/books/edition/Good_Times_for_Girls/j93k7yMKO0QC?hl=en&gbpv=1&dq=%22chord+arpeggio%22&pg=PA37&printsec=frontcover
3. https://www.google.com/books/edition/The_World_s_Best_Music_The_musician_s_gu/cxMrAAAAYAAJ?hl=en&gbpv=1&dq=%22chord+arpeggio%22&pg=PA55&printsec=frontcover

It's purely a noun in almost every dictionary though so I'm not sure. Nevertheless, I think the emphasis can be removed since it was almost definitely italicized because it's Italian.

> If you look at Chapter 11, "à la Guillaume Tell" is a quote taken from a book that Tolstoy reviewed, so I am a little hesitant to remove italics from this since it is a coherent French phrase that came from a French-language context. I don't know if I would draw the conclusion that this is referring to the opera, since this could be referring to Schiller's play or just the actual mythological figure.

Good.

> I think that rule is saying if you are referring to the letters as letters, but this is an unsemantic usage of italics for bullets in an inline list, so I think the italics should stay.

Good.

> I see what you mean about the two verses in the endnote, and have made that change, though I don't think the ellipses in the Verlaine poem represent elision. The original text of "Art poétique" has an ellipse in the last stanza. (Unless you are referring to something else? The original text of the Ariette Oubliées also has an ellipse: https://www.poemes.co/ariettes-oubliees.html

I mean the multiple dots before "And again:—" (https://archive.org/details/whatisart00tolsuoft/page/80/mode/1up). The book quotes the poem but stops after "Où l’Indécis au Précis se joint" and picks up again at "De la musique encore et toujours!". The verses between those two are "elided", which is what the dots represent. It is a bit strange since instead of just having the dots it also says "And again:—" but I don't think that changes anything.

**Comment by weijia-cheng** [comment]
Ok, I've thought about the arpeggio thing and I've removed the italics. (I actually started this project with the italics removed and second-guessed myself. Now I've second-guessed myself again!) I see what you mean about the elision in the Verlaine poem and I've made that change too. I'll submit the remaining open questions to Alex.
